// js/data.js

export const DESTINATIONS = [
  {id:1,name:'Bagasbas Beach',loc:'Daet',cat:'beach',badge:'Beach',rating:'4.9',visitors:'15K+',best:'Oct–Mar',img:'Asset/Beaches/Bagasbas Beach.jpg',desc:'The Surfing Capital of Bicol! Powerful Pacific waves stretch along golden sands. Perfect for beginners and seasoned surfers alike. One of the Philippines\' premier surfing destinations featuring consistent surf year-round.'},
  {id:2,name:'Calaguas Island',loc:'Vinzons',cat:'beach',badge:'Island',rating:'4.9',visitors:'20K+',best:'Nov–May',img:'Asset/Beaches/Calaguas Island.jpg',desc:'Home of the world-class Mahabang Buhangin — a pristine white-sand beach considered one of the most beautiful in the Philippines. Accessible only by boat, this untouched paradise is a bucket-list destination.'},
  {id:3,name:'Mercedes Siete Pecados',loc:'Mercedes',cat:'beach',badge:'Island Hopping',rating:'4.8',visitors:'10K+',best:'Jan–May',img:'Asset/Beaches/Mercedes Group of Islands.jpg',desc:'The Island-Hopping Capital of CamNorte! Seven stunning islands: Apuao Grande, Caringo, Quinapaguian, Malasugui, Apuao Pequeña, Canton, and Canimog — each with unique beaches, coral reefs, and marine life.'},
  {id:4,name:'Parola Island',loc:'Jose Panganiban',cat:'beach',badge:'Pink Sand',rating:'4.7',visitors:'5K+',best:'Nov–Apr',img:'Asset/Beaches/Parola Island.jpg',desc:'Camarines Norte\'s unique pink sand beach! A rare natural phenomenon where the sand has a rosy hue, making it one of the most Instagram-worthy and unique coastal destinations in the entire Philippines.'},
  {id:5,name:'Mt. Labo',loc:'Labo',cat:'mountain',badge:'Mountain',rating:'4.7',visitors:'6K+',best:'Dec–Apr',img:'https://i.redd.it/sea-of-clouds-in-mt-labo-camarines-nortes-highest-mountain-v0-fqksoi5o6w9d1.jpg?width=4032&format=pjpg&auto=webp&s=fea8670bf7f2a37b8dbad76a5b4d695652ca2967',desc:'The highest peak in Camarines Norte. Trek through dense rainforests to reach stunning viewpoints, encounter hidden waterfalls, and experience rich biodiversity. A challenge for trekkers of all skill levels.'},
  {id:6,name:'Chai Falls',loc:'Mercedes',cat:'falls',badge:'Waterfall',rating:'4.6',visitors:'4K+',best:'All year',img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJ9-D7rpUS6QKsVXbiElhdyNZa9LCWBPmoAMDSYJGQKDM9ITlyOh8vzyAI&s=10',desc:'A multi-tiered forest waterfall adventure in the heart of Mercedes. Crystal-clear waters cascade through lush greenery creating one of the most scenic and refreshing natural attractions in the province.'},
  {id:7,name:'Nacali Falls',loc:'San Lorenzo Ruiz',cat:'falls',badge:'Waterfall',rating:'4.7',visitors:'3K+',best:'All year',img:'https://bicoltravelguides.com/wp-content/uploads/2025/10/Bicol-Travel-Guides-Blog-Images-32.jpg',desc:'The majestic cascades of San Lorenzo — a breathtaking multi-tiered waterfall surrounded by towering trees and lush vegetation in one of the province\'s most pristine and untouched forested areas.'},
  {id:8,name:'Bantayog ni Rizal',loc:'Daet',cat:'heritage',badge:'Heritage',rating:'4.8',visitors:'12K+',best:'All year',img:'https://virmuze-bucket.s3.amazonaws.com/gallery_slideshow0/exhibit_gallery_image/2022/05/27/2944e68_exhibit_gallery_image.jpg',desc:'The FIRST José Rizal Monument in the Philippines — a historic landmark that predates even the Luneta monument in Manila. A proud symbol of Camarines Norte\'s deep love and reverence for the national hero.'},
  {id:9,name:'Black Nazarene Shrine',loc:'Capalonga',cat:'heritage',badge:'Religious Site',rating:'4.8',visitors:'18K+',best:'All year',img:'https://live.staticflickr.com/2685/4448802947_c7bf23ea92_o.jpg',desc:'A major pilgrimage destination and one of the most important religious sites in the entire Bicol Region. Thousands of faithful devotees travel from across the Philippines to venerate the miraculous Black Nazarene.'},
  {id:10,name:'Maculabo Island',loc:'Paracale',cat:'beach',badge:'Island',rating:'4.6',visitors:'8K+',best:'Feb–May',img:'https://www.hotelbeachside.com/top-10-most-beautiful-beaches-in-philippines/images/maculaboislandbeach1.jpg',desc:'A pristine island in Paracale known for its powdery white sand and crystal-clear turquoise waters. Perfect for swimming and snorkeling.'},
  {id:11,name:'Mananap Falls',loc:'San Vicente',cat:'falls',badge:'Waterfall',rating:'4.5',visitors:'5K+',best:'All year',img:'https://ik.imagekit.io/tvlk/blog/2023/08/shutterstock_1475837951-1.jpg?tr=q-70,c-at_max,w-1000,h-600',desc:'A stunning 60-foot waterfall tucked inside the lush forests of San Vicente. It requires a scenic hike, rewarding visitors with a refreshing icy plunge.'},
  {id:12,name:'Mt. Cadig',loc:'Labo',cat:'mountain',badge:'Mountain',rating:'4.6',visitors:'4K+',best:'Dec–May',img:'https://d3fphkxyf5o5bm.cloudfront.net/image-resize/format=webp,w=720/QwRY54Li1HMwD7oNfoi6o7gsWMzbmmiFPmD97EnduW',desc:'Known for its challenging trails and the nearby Cadig Cave. It offers a rewarding trek with panoramic views of the province and rich biodiversity.'},
  {id:13,name:'San Jose Beach',loc:'Talisay',cat:'beach',badge:'Beach',rating:'4.3',visitors:'6K+',best:'Mar–Jun',img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Sabang_Beach%2C_San_Jose%2C_Camarines_Sur_%282022%29.jpg/1280px-Sabang_Beach%2C_San_Jose%2C_Camarines_Sur_%282022%29.jpg',desc:'A tranquil coastal stretch in Talisay, perfect for family picnics, sunset viewing, and experiencing the local fishing culture of Camarines Norte.'},
  {id:14,name:'Colasi Falls',loc:'Mercedes',cat:'falls',badge:'Waterfall',rating:'4.7',visitors:'3K+',best:'All year',img:'https://bicoltravelguides.com/wp-content/uploads/2025/09/Bicol-Travel-Guides-Blog-Images-2025-09-02T163144.595.png',desc:'A towering 70-foot waterfall surrounded by massive rock formations. The water cascades into a deep, cool basin ideal for swimming.'}
];

export const FOODS = [
  {img:'Asset/foods/Angko.jpg',name:'Angko',loc:'Vinzons',desc:'Traditional glutinous rice cake filled with a sweet peanut mixture — chewy exterior, rich nutty filling inside.'},
  {img:'Asset/foods/Pandecillos.jpeg',name:'Pandecillos',loc:'Vinzons',desc:'Soft baked pastry filled with crushed pili nuts or sweet creamy mixture — fluffy, nutty-sweet, and utterly delicious.'},
  {img:'Asset/foods/Sinantol.jpg',name:'Sinantol',loc:'Camarines Norte',desc:'Santol fruit cooked in coconut milk with shrimp or pork — a rich balance of sour, creamy, and savory Bicolano flavors.'},
  {img:'Asset/foods/Tinumok.jpg',name:'Tinumok',loc:'Camarines Norte',desc:'Taro-leaf wraps filled with coconut meat, shrimp or pork, simmered in rich coconut milk — creamy, savory, and aromatic.'},
  {img:'Asset/foods/Kinunot.jpg',name:'Kinunot',loc:'Camarines Norte',desc:'Flaked shark or stingray in coconut milk with malunggay and spices — mildly spicy, creamy, a prized coastal heritage dish.'},
  {img:'Asset/foods/Mercedes-Tinapa.jpg',name:'Tinapa of Mercedes',loc:'Mercedes',desc:'Freshly caught fish precisely smoked in local smoking houses — glistening golden skin with a deeply aromatic, savory taste.'},
  {img:'Asset/foods/Pili-Rolls.jpg',name:'Pili Roll',loc:'Daet',desc:'Chewy cake roll filled with caramelized yema and premium native pili nuts — the perfect pasalubong.'},
  {img:'Asset/foods/Pili-Tarts.jpg',name:'Pili Tarts',loc:'Daet',desc:'Crispy tarts filled with caramelized yema and premium native pili nuts — another perfect pasalubong.'},
];

export const RESTOS = [
  {name: "Catherine's Bagasbas Lighthouse", loc: 'Daet', img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80', desc: 'A beachfront favorite offering a mix of classic Filipino dishes and refreshing drinks right by the surfing waves.'},
  {name: "Aurora's Cuisine", loc: 'Daet', img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80', desc: 'Famous for serving authentic Bicolano heirloom recipes, including their signature creamy Laing and spicy Bicol Express.'},
  {name: "This Is Earl's Food & Whatnot", loc: 'Daet', img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80', desc: 'A cozy, modern cafe known for its hearty comfort food, artisan burgers, and locally sourced coffee.'},
  {name: "Darex Lugawan", loc: 'Daet', img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80', desc: 'The ultimate late-night comfort spot. Renowned for their savory rice porridge (lugaw) topped with crispy pork and egg.'},
  {name: "Anita's Restaurant", loc: 'Vinzons', img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80', desc: 'A traditional eatery serving the best homemade Angko and hearty seafood meals caught fresh from the local ports.'},
  {name: "Bok's Kinalas", loc: 'Daet', img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80', desc: 'Serving the beloved Bicolano noodle soup, Kinalas. Their rich, slow-cooked broth and tender meat make it a local staple.'},
  {name: "Yudrei's Kinalas", loc: 'Daet', img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80', desc: 'A hidden gem for noodle lovers, offering a uniquely spiced Kinalas broth and a very relaxed, local street-food ambiance.'},
  {name: "Lomi Hauz", loc: 'Daet', img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80', desc: 'Specializing in thick, piping hot bowls of Lomi overloaded with toppings like chicharon, meatballs, and liver.'},
  {name: "Baked by Baby", loc: 'Daet', img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80', desc: 'A beloved local bakery and cafe offering fresh pastries, custom cakes, and the sweetest Pili nut desserts in town.'},
  {name: "Jannah's Pasalubong", loc: 'Daet', img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80', desc: 'Your one-stop shop for everything sweet in CamNorte! Famous for their Pili tarts and classic Bicolano snacks.'},
  {name: "Chef Tiu's Signature", loc: 'Daet', img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80', desc: 'An upscale dining experience fusing international techniques with fresh, locally sourced Bicolano ingredients.'},
  {name: "Hoogpaan Restaurant", loc: 'Bagasbas', img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80', desc: 'A vibrant surf-themed restobar. Perfect for unwinding with ice-cold drinks, grilled seafood, and live acoustic music.'},
  {name: "Alvinos Roast Grill & Fry", loc: 'Daet', img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80', desc: 'The go-to place for meat lovers, featuring perfectly roasted chicken, smoky barbecue, and deep-fried local favorites.'},
  {name: "Lugawan sa Bagasbas", loc: 'Daet', img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80', desc: 'Warm up after a morning surf session with a steaming bowl of affordable and delicious lugaw right by the beach.'},
  {name: "Tina's Eatery", loc: 'Mercedes', img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80', desc: 'An authentic turo-turo experience offering home-cooked Sinantol and Kinunot straight from the Mercedes fish port.'},
  {name: "Jybon Chicken Inasal", loc: 'Daet', img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80', desc: 'Satisfy your cravings with perfectly grilled, authentic Chicken Inasal served with unlimited rice and savory chicken oil.'},
  {name: "Reichan Tabeya", loc: 'Daet', img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80', desc: 'A unique fusion spot offering Japanese-inspired street food and sushi alongside comforting local dishes.'},
  {name: "Pan Pao (Pansit at Siopao)", loc: 'Daet', img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80', desc: 'A classic merienda destination famous for their massive, fluffy siopao and flavorful, freshly tossed pansit.'}
];

export const FESTIVALS = [
  {month:'June',name:'Pinyasan Festival',town:'Daet',desc:'Colorful celebration of the famous sweet Formosa Pineapple of Daet, one of the most famous festivals in the province.',img:'Asset/festival/pinyasanfestival.jpg'},
  {month:'June',name:'Mambulawan Festival',town:'Jose Panganiban',desc:'"Mambulawan" means gold — showcasing the rich gold mining heritage of Jose Panganiban since the Spanish era.',img:'Asset/festival/mambulawanfestival-josepanganiban.jpg'},
  {month:'August 1–8',name:'Kadagatan Festival',town:'Mercedes',desc:'"Kadagatan" means ocean — celebrating the fish industry and the people\'s deep connection to the sea.',img:'Asset/festival/kadagatanfestival.jpg'},
  {month:'October 18–24',name:'Rahugan Festival',town:'Basud',desc:'Honoring St. Raphael the Archangel — "Rahugan" means group of coconuts, symbolizing unity and prosperity since 2008.',img:'Asset/festival/rahuganfestival-basud.jpg'},
  {month:'September (1st week)',name:'Busig-on Festival',town:'Labo',desc:'Celebrating heroism, unity, peace, and Bicolano values. "Busig" means water, representing abundance in Labo.',img:'Asset/festival/busig-on-labo.jpg'},
  {month:'June 24–29',name:'Babakasin Festival',town:'Vinzons',desc:'Promoting local delicacies. Coincides with the feast of St. Peter the Apostle.',img:'https://images.unsplash.com/photo-1533174000222-1d5afba26099?w=600&q=80'},
  {month:'Summer Season',name:'Mananap Festival',town:'San Vicente',desc:'Showcasing Mananap Falls and promoting eco-tourism, environmental awareness, and conservation in San Vicente.',img:'Asset/festival/mananapfestival.jpg'},
  {month:'Annual',name:'Pabirik Festival',town:'Paracale',desc:'Celebrating gold mining heritage and honoring Our Lady of Candelaria. "Pabirik" is the traditional gold ore processing method.',img:'Asset/festival/pabirikfestival.jpg'},
  {month:'Annual',name:'Paruyan Festival',town:'Talisay',desc:'"Paruy" means rice — honoring the agricultural heritage and hard-working farmers of Talisay.',img:'Asset/festival/paruyanfestival.jpg'},
  {month:'Annual',name:'Boyoboy Festival',town:'San Lorenzo Ruiz',desc:'Promoting the pineapple industry and the role of agriculture in the community development of San Lorenzo Ruiz.',img:'Asset/festival/boyuboyfestival.jpg'},
  {month:'Annual',name:'Palong Festival',town:'Capalonga',desc:'Agricultural thanksgiving combined with deep religious devotion to the Black Nazarene, the municipality\'s patron.',img:'Asset/festival/palongfestival.jpg'},
  {month:'Annual',name:'Padayog Festival',town:'Santa Elena',desc:'Combines palay (rice) and niyog (coconut) — honoring farmers and coconut growers with street dancing, cultural presentations, and agricultural fairs.',img:'Asset/festival/padayogfestival.jpeg'},
];

export const MUNIS = [
  {name:'Daet',badge:'Capital City',img:'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=600&q=80',desc:'Surfing Capital of Bicol · First Rizal Monument · Sweet Formosa Pineapple · Cory Aquino Blvd (8.7km)'},
  {name:'Talisay',badge:'Agricultural',img:'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=600&q=80',desc:'San Jose Beach · Coastal & Agricultural Landscapes · Paruyan Festival · Countryside Charm'},
  {name:'Vinzons',badge:'Heritage',img:'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=600&q=80',desc:'Calaguas Islands · Mt. Panit · Birthplace of W.Q. Vinzons · Angko & Pandecillos · St. Peter Apostle Church'},
  {name:'Labo',badge:'Adventure',img:'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=600&q=80',desc:'Mt. Labo & Mt. Cadig · Birthplace of Gen. Vicente Lukban · Waterfalls, Caves & Mountain Adventures'},
  {name:'San Vicente',badge:'Eco-Tourism',img:'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=600&q=80',desc:'Agricultural Heartland · Mananap Falls · Vast Rice Fields · Mananap Festival · Rural Traditions'},
  {name:'San Lorenzo Ruiz',badge:'Eco-Adventure',img:'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=600&q=80',desc:'Longest Zipline in Bicol · Nacali Falls · Bicol Natural Park · Untouched Forests & River Systems'},
  {name:'Mercedes',badge:'Marine',img:'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=600&q=80',desc:'Island-Hopping Capital · Siete Pecados Islands · Mercedes Fish Port · Tinapa, Daing, Tuyo Industry'},
  {name:'Basud',badge:'Nature',img:'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=600&q=80',desc:'Giant Mother Tree (Red Lauan) · Hidden Beaches · First WWII Guerrilla Stand at Laniton (Dec 18, 1941)'},
  {name:'Capalonga',badge:'Pilgrimage',img:'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=600&q=80',desc:'Black Nazarene Shrine · Major Pilgrimage Center of Bicol · Capalonga Lighthouse · Where Faith Meets Sea'},
  {name:'Jose Panganiban',badge:'Mining',img:'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=600&q=80',desc:'Pink Sands of Parola Island · Mining Heritage · Named after José Panganiban · Turayo View Deck'},
  {name:'Paracale',badge:'Gold Capital',img:'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=600&q=80',desc:'Gold Capital of Bicol · Pabirik Festival · Nuestra Señora de Candelaria · Centuries-Old Gold Mining'},
  {name:'Santa Elena',badge:'Agri-Tourism',img:'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=600&q=80',desc:'Northern Forests · Coconut Plantations · Agri-Tourism Haven · Rolling Countryside Landscapes'},
];