// js/data.js

export const DESTINATIONS = [
  {
    id: 1,
    name: "Bagasbas Beach",
    loc: "Daet",
    cat: "beach",
    badge: "Beach",
    rating: "4.9",
    visitors: "15K+",
    best: "Oct–Mar",
    img: "Asset/Beaches/Bagasbas Beach.jpg",
    desc: "The Surfing Capital of Bicol! Powerful Pacific waves stretch along golden sands. Perfect for beginners and seasoned surfers alike. One of the Philippines' premier surfing destinations featuring consistent surf year-round.",
  },
  {
    id: 2,
    name: "Calaguas Island",
    loc: "Vinzons",
    cat: "beach",
    badge: "Island",
    rating: "4.9",
    visitors: "20K+",
    best: "Nov–May",
    img: "Asset/Beaches/Calaguas Island.jpg",
    desc: "Home of the world-class Mahabang Buhangin — a pristine white-sand beach considered one of the most beautiful in the Philippines. Accessible only by boat, this untouched paradise is a bucket-list destination.",
  },
  {
    id: 3,
    name: "Mercedes Siete Pecados",
    loc: "Mercedes",
    cat: "beach",
    badge: "Island Hopping",
    rating: "4.8",
    visitors: "10K+",
    best: "Jan–May",
    img: "Asset/Beaches/Mercedes Group of Islands.jpg",
    desc: "The Island-Hopping Capital of CamNorte! Seven stunning islands: Apuao Grande, Caringo, Quinapaguian, Malasugui, Apuao Pequeña, Canton, and Canimog — each with unique beaches, coral reefs, and marine life.",
  },
  {
    id: 4,
    name: "Parola Island",
    loc: "Jose Panganiban",
    cat: "beach",
    badge: "Pink Sand",
    rating: "4.7",
    visitors: "5K+",
    best: "Nov–Apr",
    img: "Asset/Beaches/Parola Island.jpg",
    desc: "Camarines Norte's unique pink sand beach! A rare natural phenomenon where the sand has a rosy hue, making it one of the most Instagram-worthy and unique coastal destinations in the entire Philippines.",
  },
  {
    id: 5,
    name: "Mt. Labo",
    loc: "Labo",
    cat: "mountain",
    badge: "Mountain",
    rating: "4.7",
    visitors: "6K+",
    best: "Dec–Apr",
    img: "Asset/Mountain_View_Deck/Mt. Labo.jpg",
    desc: "The highest peak in Camarines Norte. Trek through dense rainforests to reach stunning viewpoints, encounter hidden waterfalls, and experience rich biodiversity. A challenge for trekkers of all skill levels.",
  },
  {
    id: 6,
    name: "Chai Falls",
    loc: "Mercedes",
    cat: "falls",
    badge: "Waterfall",
    rating: "4.6",
    visitors: "4K+",
    best: "All year",
    img: "Asset/Rivers_Falls/Chai Falls.jpg",
    desc: "A multi-tiered forest waterfall adventure in the heart of Mercedes. Crystal-clear waters cascade through lush greenery creating one of the most scenic and refreshing natural attractions in the province.",
  },
  {
    id: 7,
    name: "Nacali Falls",
    loc: "San Lorenzo Ruiz",
    cat: "falls",
    badge: "Waterfall",
    rating: "4.7",
    visitors: "3K+",
    best: "All year",
    img: "Asset/Rivers_Falls/Nacali Falls.jpg",
    desc: "The majestic cascades of San Lorenzo — a breathtaking multi-tiered waterfall surrounded by towering trees and lush vegetation in one of the province's most pristine and untouched forested areas.",
  },
  {
    id: 8,
    name: "Bantayog ni Rizal",
    loc: "Daet",
    cat: "heritage",
    badge: "Heritage",
    rating: "4.8",
    visitors: "12K+",
    best: "All year",
    img: "Asset/Historical_Religious_Sites/Unang Bantayog ni Rizal.jpg",
    desc: "The FIRST José Rizal Monument in the Philippines — a historic landmark that predates even the Luneta monument in Manila. A proud symbol of Camarines Norte's deep love and reverence for the national hero.",
  },
  {
    id: 9,
    name: "Black Nazarene Shrine",
    loc: "Capalonga",
    cat: "heritage",
    badge: "Religious Site",
    rating: "4.8",
    visitors: "18K+",
    best: "All year",
    img: "Asset/Historical_Religious_Sites/Shrine of Jesus the Black Nazarene.jpg",
    desc: "A major pilgrimage destination and one of the most important religious sites in the entire Bicol Region. Thousands of faithful devotees travel from across the Philippines to venerate the miraculous Black Nazarene.",
  },
  {
    id: 10,
    name: "Maculabo Island",
    loc: "Paracale",
    cat: "beach",
    badge: "Island",
    rating: "4.6",
    visitors: "8K+",
    best: "Feb–May",
    img: "Asset/Beaches/Maculabo Island.jpg",
    desc: "A pristine island in Paracale known for its powdery white sand and crystal-clear turquoise waters. Perfect for swimming and snorkeling.",
  },
  {
    id: 11,
    name: "Mananap Falls",
    loc: "San Vicente",
    cat: "falls",
    badge: "Waterfall",
    rating: "4.5",
    visitors: "5K+",
    best: "All year",
    img: "Asset/Rivers_Falls/Mananap Falls.jpeg",
    desc: "A stunning 60-foot waterfall tucked inside the lush forests of San Vicente. It requires a scenic hike, rewarding visitors with a refreshing icy plunge.",
  },
  {
    id: 12,
    name: "Mt. Cadig",
    loc: "Labo",
    cat: "mountain",
    badge: "Mountain",
    rating: "4.6",
    visitors: "4K+",
    best: "Dec–May",
    img: "Asset/Mountain_View_Deck/Mt.Cadig.jpg",
    desc: "Known for its challenging trails and the nearby Cadig Cave. It offers a rewarding trek with panoramic views of the province and rich biodiversity.",
  },
  {
    id: 13,
    name: "San Jose Beach",
    loc: "Talisay",
    cat: "beach",
    badge: "Beach",
    rating: "4.3",
    visitors: "6K+",
    best: "Mar–Jun",
    img: "Asset/Beaches/San Jose Beach.jpg",
    desc: "A tranquil coastal stretch in Talisay, perfect for family picnics, sunset viewing, and experiencing the local fishing culture of Camarines Norte.",
  },
  {
    id: 14,
    name: "Colasi Falls",
    loc: "Mercedes",
    cat: "falls",
    badge: "Waterfall",
    rating: "4.7",
    visitors: "3K+",
    best: "All year",
    img: "Asset/Rivers_Falls/Colasi Falls.jpg",
    desc: "A towering 70-foot waterfall surrounded by massive rock formations. The water cascades into a deep, cool basin ideal for swimming.",
  },
  {
    id: 15,
    name: "Apuao Grande Beach",
    loc: "Mercedes",
    cat: "beach",
    badge: "Island Hopping",
    rating: "4.8",
    visitors: "10K+",
    best: "Jan–May",
    img: "Asset/Beaches/Apuao Grande.jpg",
    desc: "A stunning island within the Siete Pecados group known for its picturesque Agoho (pine-like) trees and long stretches of pristine white sand. Perfect for camping and beach bumming.",
  },
  {
    id: 16,
    name: "Apuao Pequena Beach",
    loc: "Mercedes",
    cat: "beach",
    badge: "Island Hopping",
    rating: "4.8",
    visitors: "10K+",
    best: "Jan–May",
    img: "Asset/Beaches/Apuao Pequena.jpg",
    desc: "Connected to Apuao Grande by a beautiful white sandbar. This island features a dense mangrove forest and a bat cave, offering a unique mix of beach relaxation and eco-adventure.",
  },
  {
    id: 17,
    name: "Candelaria Beach",
    loc: "Paracale",
    cat: "beach",
    badge: "Beach",
    rating: "4.4",
    visitors: "4K+",
    best: "Feb–May",
    img: "Asset/Beaches/Candelaria Beach.jpg",
    desc: "A peaceful coastal retreat in the gold-town of Paracale. Candelaria Beach offers a quiet, uncrowded shoreline ideal for a relaxing getaway and witnessing the beautiful Bicolano sunset.",
  },
  {
    id: 18,
    name: "Caringo Island",
    loc: "Mercedes",
    cat: "beach",
    badge: "Island Hopping",
    rating: "4.8",
    visitors: "10K+",
    best: "Jan–May",
    img: "Asset/Beaches/Caringo Island.jpg",
    desc: "The oldest settlement among the Siete Pecados islands. It features a thriving fish sanctuary for snorkeling enthusiasts and the oldest house in Mercedes, blending history with marine beauty.",
  },
  {
    id: 19,
    name: "Gumaus Beach",
    loc: "Paracale",
    cat: "beach",
    badge: "Beach",
    rating: "4.7",
    visitors: "9K+",
    best: "Mar–Jun",
    img: "Asset/Beaches/Gumaus Beach.jpg",
    desc: "Often dubbed as the 'Small Boracay' of Camarines Norte. Gumaus Beach boasts powdery white sand and crystal-clear waters, making it one of the premier beach destinations in the province.",
  },
  {
    id: 20,
    name: "Malasugui Beach",
    loc: "Mercedes",
    cat: "beach",
    badge: "Island Hopping",
    rating: "4.8",
    visitors: "10K+",
    best: "Jan–May",
    img: "Asset/Beaches/Mercedes Group of Islands.jpg",
    desc: "The Island-Hopping Capital of CamNorte! Seven stunning islands: Apuao Grande, Caringo, Quinapaguian, Malasugui, Apuao Pequeña, Canton, and Canimog — each with unique beaches, coral reefs, and marine life.",
  },
  {
    id: 21,
    name: "Matoogtoog Beach",
    loc: "Mercedes",
    cat: "beach",
    badge: "Island Hopping",
    rating: "4.8",
    visitors: "10K+",
    best: "Jan–May",
    img: "Asset/Beaches/Mercedes Group of Islands.jpg",
    desc: "The Island-Hopping Capital of CamNorte! Seven stunning islands: Apuao Grande, Caringo, Quinapaguian, Malasugui, Apuao Pequeña, Canton, and Canimog — each with unique beaches, coral reefs, and marine life.",
  },
  {
    id: 22,
    name: "Quinamanuca Beach",
    loc: "Mercedes",
    cat: "beach",
    badge: "Island Hopping",
    rating: "4.8",
    visitors: "10K+",
    best: "Jan–May",
    img: "Asset/Beaches/Mercedes Group of Islands.jpg",
    desc: "The Island-Hopping Capital of CamNorte! Seven stunning islands: Apuao Grande, Caringo, Quinapaguian, Malasugui, Apuao Pequeña, Canton, and Canimog — each with unique beaches, coral reefs, and marine life.",
  },
  {
    id: 23,
    name: "Taba-Taba Beach",
    loc: "Mercedes",
    cat: "beach",
    badge: "Island Hopping",
    rating: "4.8",
    visitors: "10K+",
    best: "Jan–May",
    img: "Asset/Beaches/Mercedes Group of Islands.jpg",
    desc: "The Island-Hopping Capital of CamNorte! Seven stunning islands: Apuao Grande, Caringo, Quinapaguian, Malasugui, Apuao Pequeña, Canton, and Canimog — each with unique beaches, coral reefs, and marine life.",
  },
  {
    id: 24,
    name: "Tinakubtakuban Pebble Beach",
    loc: "Mercedes",
    cat: "beach",
    badge: "Island Hopping",
    rating: "4.8",
    visitors: "10K+",
    best: "Jan–May",
    img: "Asset/Beaches/Mercedes Group of Islands.jpg",
    desc: "The Island-Hopping Capital of CamNorte! Seven stunning islands: Apuao Grande, Caringo, Quinapaguian, Malasugui, Apuao Pequeña, Canton, and Canimog — each with unique beaches, coral reefs, and marine life.",
  },
];

export const FOODS = [
  {
    img: "Asset/foods/Angko.jpg",
    name: "Angko",
    loc: "Vinzons",
    desc: "Traditional glutinous rice cake filled with a sweet peanut mixture — chewy exterior, rich nutty filling inside.",
  },
  {
    img: "Asset/foods/Pandecillos.jpeg",
    name: "Pandecillos",
    loc: "Vinzons",
    desc: "Soft baked pastry filled with crushed pili nuts or sweet creamy mixture — fluffy, nutty-sweet, and utterly delicious.",
  },
  {
    img: "Asset/foods/Sinantol.jpg",
    name: "Sinantol",
    loc: "Camarines Norte",
    desc: "Santol fruit cooked in coconut milk with shrimp or pork — a rich balance of sour, creamy, and savory Bicolano flavors.",
  },
  {
    img: "Asset/foods/Tinumok.jpg",
    name: "Tinumok",
    loc: "Camarines Norte",
    desc: "Taro-leaf wraps filled with coconut meat, shrimp or pork, simmered in rich coconut milk — creamy, savory, and aromatic.",
  },
  {
    img: "Asset/foods/Kinunot.jpg",
    name: "Kinunot",
    loc: "Camarines Norte",
    desc: "Flaked shark or stingray in coconut milk with malunggay and spices — mildly spicy, creamy, a prized coastal heritage dish.",
  },
  {
    img: "Asset/foods/Mercedes-Tinapa.jpg",
    name: "Tinapa of Mercedes",
    loc: "Mercedes",
    desc: "Freshly caught fish precisely smoked in local smoking houses — glistening golden skin with a deeply aromatic, savory taste.",
  },
  {
    img: "Asset/foods/Pili-Rolls.jpg",
    name: "Pili Roll",
    loc: "Daet",
    desc: "Chewy cake roll filled with caramelized yema and premium native pili nuts — the perfect pasalubong.",
  },
  {
    img: "Asset/foods/Pili-Tarts.jpg",
    name: "Pili Tarts",
    loc: "Daet",
    desc: "Crispy tarts filled with caramelized yema and premium native pili nuts — another perfect pasalubong.",
  },
];

export const RESTOS = [
  {
    name: "Catherine's Bagasbas Lighthouse",
    loc: "Daet",
    img: "Asset/restaurants/Catherine_s Bagasbas Lighthouse and Resort.jpg",
    desc: "A beachfront favorite offering a mix of classic Filipino dishes and refreshing drinks right by the surfing waves.",
  },
  {
    name: "Aurora's Cuisine",
    loc: "Daet",
    img: "Asset/restaurants/Aurora_s Cuisine.jpg",
    desc: "Famous for serving authentic Bicolano heirloom recipes, including their signature creamy Laing and spicy Bicol Express.",
  },
  {
    name: "This Is Earl's Food & Whatnot",
    loc: "Daet",
    img: "Asset/restaurants/This Is Earl_s & Whatnot.jpg",
    desc: "A cozy, modern cafe known for its hearty comfort food, artisan burgers, and locally sourced coffee.",
  },
  {
    name: "Anita's Restaurant",
    loc: "Vinzons",
    img: "Asset/restaurants/Anita_s Restaurant.jpg",
    desc: "A traditional eatery serving the best homemade Angko and hearty seafood meals caught fresh from the local ports.",
  },
  {
    name: "Bok's Kinalas",
    loc: "Daet",
    img: "Asset/restaurants/Bok_s Kinalas.jpg",
    desc: "Serving the beloved Bicolano noodle soup, Kinalas. Their rich, slow-cooked broth and tender meat make it a local staple.",
  },
  {
    name: "Yudrei's Kinalas",
    loc: "Daet",
    img: "Asset/restaurants/Yudrei_s Kinalas.jpg",
    desc: "A hidden gem for noodle lovers, offering a uniquely spiced Kinalas broth and a very relaxed, local street-food ambiance.",
  },
  {
    name: "Lomi Hauz",
    loc: "Daet",
    img: "Asset/restaurants/Lomi Hauz & View Deck.jpg",
    desc: "Specializing in thick, piping hot bowls of Lomi overloaded with toppings like chicharon, meatballs, and liver.",
  },
  {
    name: "Baked by Baby",
    loc: "Daet",
    img: "Asset/restaurants/Baked by Baby.jpg",
    desc: "A beloved local bakery and cafe offering fresh pastries, custom cakes, and the sweetest Pili nut desserts in town.",
  },
  {
    name: "Jannah's Pasalubong",
    loc: "Daet",
    img: "Asset/restaurants/Jannah_s Pasalubong.jpg",
    desc: "Your one-stop shop for everything sweet in CamNorte! Famous for their Pili tarts and classic Bicolano snacks.",
  },
  {
    name: "Chef Tiu's Signature",
    loc: "Daet",
    img: "Asset/restaurants/Chef Tiu_s Signature.jpg",
    desc: "An upscale dining experience fusing international techniques with fresh, locally sourced Bicolano ingredients.",
  },
  {
    name: "Hoogpaan Restaurant",
    loc: "Bagasbas",
    img: "Asset/restaurants/Hoogpaan.jpg",
    desc: "A vibrant surf-themed restobar. Perfect for unwinding with ice-cold drinks, grilled seafood, and live acoustic music.",
  },
  {
    name: "Alvinos Roast Grill & Fry",
    loc: "Daet",
    img: "Asset/restaurants/Alvinos.jpg",
    desc: "The go-to place for meat lovers, featuring perfectly roasted chicken, smoky barbecue, and deep-fried local favorites.",
  },
  {
    name: "Lugawan sa Bagasbas",
    loc: "Daet",
    img: "Asset/restaurants/Lugawan sa Bagasbas.jpg",
    desc: "Warm up after a morning surf session with a steaming bowl of affordable and delicious lugaw right by the beach.",
  },
  {
    name: "Tina's Eatery",
    loc: "Mercedes",
    img: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80",
    desc: "An authentic turo-turo experience offering home-cooked Sinantol and Kinunot straight from the Mercedes fish port.",
  },
  {
    name: "Jybon Chicken Inasal",
    loc: "Daet",
    img: "Asset/restaurants/Jybon Chicken Inasal.jpg",
    desc: "Satisfy your cravings with perfectly grilled, authentic Chicken Inasal served with unlimited rice and savory chicken oil.",
  },
  {
    name: "Reichan Tabeya",
    loc: "Daet",
    img: "Asset/restaurants/Reichan Tabeya.jpg",
    desc: "A unique fusion spot offering Japanese-inspired street food and sushi alongside comforting local dishes.",
  },
  {
    name: "Pan Pao (Pansit at Siopao)",
    loc: "Daet",
    img: "Asset/restaurants/Pan Pao.jpg",
    desc: "A classic merienda destination famous for their massive, fluffy siopao and flavorful, freshly tossed pansit.",
  },
];

export const FESTIVALS = [
  {
    month: "June",
    name: "Pinyasan Festival",
    town: "Daet",
    desc: "Colorful celebration of the famous sweet Formosa Pineapple of Daet, one of the most famous festivals in the province.",
    img: "Asset/festival/pinyasanfestival.jpg",
  },
  {
    month: "June",
    name: "Mambulawan Festival",
    town: "Jose Panganiban",
    desc: '"Mambulawan" means gold — showcasing the rich gold mining heritage of Jose Panganiban since the Spanish era.',
    img: "Asset/festival/mambulawanfestival-josepanganiban.jpg",
  },
  {
    month: "August 1–8",
    name: "Kadagatan Festival",
    town: "Mercedes",
    desc: '"Kadagatan" means ocean — celebrating the fish industry and the people\'s deep connection to the sea.',
    img: "Asset/festival/kadagatanfestival.jpg",
  },
  {
    month: "October 18–24",
    name: "Rahugan Festival",
    town: "Basud",
    desc: 'Honoring St. Raphael the Archangel — "Rahugan" means group of coconuts, symbolizing unity and prosperity since 2008.',
    img: "Asset/festival/rahuganfestival-basud.jpg",
  },
  {
    month: "September (1st week)",
    name: "Busig-on Festival",
    town: "Labo",
    desc: 'Celebrating heroism, unity, peace, and Bicolano values. "Busig" means water, representing abundance in Labo.',
    img: "Asset/festival/busig-on-labo.jpg",
  },
  {
    month: "June 24–29",
    name: "Babakasin Festival",
    town: "Vinzons",
    desc: "Promoting local delicacies. Coincides with the feast of St. Peter the Apostle.",
    img: "https://images.unsplash.com/photo-1533174000222-1d5afba26099?w=600&q=80",
  },
  {
    month: "Summer Season",
    name: "Mananap Festival",
    town: "San Vicente",
    desc: "Showcasing Mananap Falls and promoting eco-tourism, environmental awareness, and conservation in San Vicente.",
    img: "Asset/festival/mananapfestival.jpg",
  },
  {
    month: "Annual",
    name: "Pabirik Festival",
    town: "Paracale",
    desc: 'Celebrating gold mining heritage and honoring Our Lady of Candelaria. "Pabirik" is the traditional gold ore processing method.',
    img: "Asset/festival/pabirikfestival.JPG",
  },
  {
    month: "Annual",
    name: "Paruyan Festival",
    town: "Talisay",
    desc: '"Paruy" means rice — honoring the agricultural heritage and hard-working farmers of Talisay.',
    img: "Asset/festival/paruyanfestival.jpg",
  },
  {
    month: "Annual",
    name: "Boyoboy Festival",
    town: "San Lorenzo Ruiz",
    desc: "Promoting the pineapple industry and the role of agriculture in the community development of San Lorenzo Ruiz.",
    img: "Asset/festival/boyuboyfestival.jpg",
  },
  {
    month: "Annual",
    name: "Palong Festival",
    town: "Capalonga",
    desc: "Agricultural thanksgiving combined with deep religious devotion to the Black Nazarene, the municipality's patron.",
    img: "Asset/festival/palongfestival.jpg",
  },
  {
    month: "Annual",
    name: "Padayog Festival",
    town: "Santa Elena",
    desc: "Combines palay (rice) and niyog (coconut) — honoring farmers and coconut growers with street dancing, cultural presentations, and agricultural fairs.",
    img: "Asset/festival/padayogfestival.jpeg",
  },
];

export const MUNIS = [
  {
    name: "Daet",
    badge: "Capital City",
    img: "Asset/Municipality_Town/Daet.jpg",
    desc: "Surfing Capital of Bicol · First Rizal Monument · Sweet Formosa Pineapple · Cory Aquino Blvd (8.7km)",
  },
  {
    name: "Talisay",
    badge: "Agricultural",
    img: "Asset/Municipality_Town/TALISAY.jpg",
    desc: "San Jose Beach · Coastal & Agricultural Landscapes · Paruyan Festival · Countryside Charm",
  },
  {
    name: "Vinzons",
    badge: "Heritage",
    img: "Asset/Municipality_Town/VINZONS.jpg",
    desc: "Calaguas Islands · Mt. Panit · Birthplace of W.Q. Vinzons · Angko & Pandecillos · St. Peter Apostle Church",
  },
  {
    name: "Labo",
    badge: "Adventure",
    img: "Asset/Municipality_Town/LABO.jpg",
    desc: "Mt. Labo & Mt. Cadig · Birthplace of Gen. Vicente Lukban · Waterfalls, Caves & Mountain Adventures",
  },
  {
    name: "San Vicente",
    badge: "Eco-Tourism",
    img: "Asset/Municipality_Town/SAN VICENTE.jpg",
    desc: "Agricultural Heartland · Mananap Falls · Vast Rice Fields · Mananap Festival · Rural Traditions",
  },
  {
    name: "San Lorenzo Ruiz",
    badge: "Eco-Adventure",
    img: "Asset/Municipality_Town/SAN LORENZO RUIZ.jpg",
    desc: "Longest Zipline in Bicol · Nacali Falls · Bicol Natural Park · Untouched Forests & River Systems",
  },
  {
    name: "Mercedes",
    badge: "Marine",
    img: "Asset/Municipality_Town/MERCEDES.jpg",
    desc: "Island-Hopping Capital · Siete Pecados Islands · Mercedes Fish Port · Tinapa, Daing, Tuyo Industry",
  },
  {
    name: "Basud",
    badge: "Nature",
    img: "Asset/Municipality_Town/BASUD.jpg",
    desc: "Giant Mother Tree (Red Lauan) · Hidden Beaches · First WWII Guerrilla Stand at Laniton (Dec 18, 1941)",
  },
  {
    name: "Capalonga",
    badge: "Pilgrimage",
    img: "Asset/Municipality_Town/CAPALONGA.jpg",
    desc: "Black Nazarene Shrine · Major Pilgrimage Center of Bicol · Capalonga Lighthouse · Where Faith Meets Sea",
  },
  {
    name: "Jose Panganiban",
    badge: "Mining",
    img: "Asset/Municipality_Town/JOSE PANGANIBAN.jpg",
    desc: "Pink Sands of Parola Island · Mining Heritage · Named after José Panganiban · Turayo View Deck",
  },
  {
    name: "Paracale",
    badge: "Gold Capital",
    img: "Asset/Municipality_Town/PARACALE.jpg",
    desc: "Gold Capital of Bicol · Pabirik Festival · Nuestra Señora de Candelaria · Centuries-Old Gold Mining",
  },
  {
    name: "Santa Elena",
    badge: "Agri-Tourism",
    img: "Asset/Municipality_Town/SANTA ELENA.jpg",
    desc: "Northern Forests · Coconut Plantations · Agri-Tourism Haven · Rolling Countryside Landscapes",
  },
];
